---
title: "IODS-final"
author: 
- Heidi Maanonen
- heidi.maanonen@helsinki.fi
date: "26.2.2017"
output: 
  html_document:
    theme: sandstone
    highlight: tango
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    number_sections: true
    toc_depth: 2
    fig_caption: true
    fig_width: 6
    fig_height: 4
    code_folding: hide
---

&nbsp;

# The purpose of the final work

&nbsp;

The idea of the this final work is to show and demonstrate what I have been learning about R, data visualizing and statistics during this course called **Introduction to Open Data Science**. The course is organized by [University of Helsinki](https://wiki.helsinki.fi/display/SocStats/Introduction+to+Open+Data+Science,+spring+2017). I really want highlight that this was and is my first course and work with R programming. Considering this I like to believe that I have learnt a lot of very interesting ways of using R, RStudio and Rpackages.

In this final work We have 2 options of choosing our data. First we could use one of the the datasets which we had already applied. Alternatively we could try to find a new dataset from internet in terms of our interests or just to raise the degree of difficulty, I think. And because I'm very interested in research I wanted to find a new dataset to learn how to do the whole data wrangling and exploring process by myself. 

My intention here is to deepen my knowledge on [Principal Component Analysis](https://en.wikipedia.org/wiki/Principal_component_analysis) in terms of finding some latent structure of the dataset introduced in the next chapter.  

&nbsp;

# Description of the dataset

&nbsp;


I choose the dataset from [Kaggle](https://www.kaggle.com/miroslavsabo/young-people-survey), which is about **Preferencies, interests, habits, opinions and fears of young people** in Slovakia. In 2013, students of the Statistics class at [FSEV UK](https://fses.uniba.sk/en/) were asked to invite their friends to participate in this survey. Accordingly they managed to get 1 010 participants for this purpose. 

If you take a look at the Kaggle link you can see that there are huge amount of variables, that is 150 columns mainly integers but also some categorical variables. Thus for the purpose of this assignment and Principal Component Analysis I had to choose some interesting content which is funny because I choose the interests and hobbies of these young people. In addition, I also wanted to count in some demographical variables to make visualizations more versatile.

&nbsp;

## First part of data wrangling 

&nbsp;


You can find all of the datasets from my [GitHub Repository](https://github.com/8475394/IODS-final/tree/master/Data). The CSV-file called "raw_young_people_survey" is the original dataset from Kaggle. The "create_interests.R" is the R Script file of my data wrangling and the "interests.txt" is the file what I'm going to use here.

&nbsp;

<p class="text-warning">BRIEF DESCRIPTION OF DATA WRANGLING PHASES:</p>

1. Reading the whole dataset
2. Selecting the variables of interests and hobbies including age and gender
3. Renaming some variables
4. Exploring missing values
5. Removing the rows with missing values
6. Saving the new data


&nbsp;

## Introducing the variables 

&nbsp;


```{r, message=FALSE, warning=FALSE}
# Reading the data with interests and demographics
interests_dem <- read.table(file.path("C:/Users/heidi/Documents/YLIOPISTO/TILASTOTIEDE/INTRODUCTION TO OPEN DATA SCIENCE/IODS-final/data", "interests_dem.txt"), header = TRUE)

# Printing the data structure
library(dplyr)
glimpse(interests_dem)
```


&nbsp;



  

&nbsp;



